pipeline {

	agent any
	
	stages {
	
		stage('Compile Stage') {
			steps {
				withMaven(maven: 'MVN_3_9_6') {
					sh 'mvn -f com.corso.jenkins/pom.xml clean compile'
				}
			}			
		}
		
		
		stage('Testing Stage') {
			steps {
				withMaven(maven: 'MVN_3_9_6') {
					sh 'mvn -f com.corso.jenkins/pom.xml test'
				}
			}		
    
			post {
                success {
                    junit '**/com.corso.jenkins/target/surefire-reports/TEST-*.xml'
                    // archiveArtifacts 'target/*.jar'
                }
            }		
		}
		
		stage('Package') {
			steps {
				withMaven(maven: 'MVN_3_9_6') {
					sh 'mvn -f com.corso.jenkins/pom.xml install'
				}
			}
		}
	
		
		
	}

}