pipeline {

	agent any
	
	stages {
	
		stage('Compile Stage') {
			steps {
				withMaven(maven: 'maven_3_5_0') {
				    sh 'cd com.corso.jenkins'
					sh 'mvn clean compile'
				}
			}			
		}
		
		
		stage('Testing Stage') {
			steps {
				withMaven(maven: 'maven_3_5_0') {
					sh 'cd com.corso.jenkins'
					sh 'mvn test'
				}
			}			
		}
		
		stage('Deployment Stage') {
			steps {
				withMaven(maven: 'maven_3_5_0') {
					sh 'cd com.corso.jenkins'
					sh 'mvn deploy'
				}
			}
		}
	
	}

}