pipeline {

	agent any
	
	stages {
	
		stage('Compile Stage') {
			steps {
				withMaven(maven: 'maven_3_8_6') {
					sh 'mvn -f com.corso.jenkins/pom.xml clean compile'
				}
			}			
		}
		
		
		stage('Testing Stage') {
			steps {
				withMaven(maven: 'maven_3_8_6') {
					sh 'mvn -f com.corso.jenkins/pom.xml test'
				}
			}			
		}
		
		//stage('Deployment Stage') {
		//	steps {
		//		withMaven(maven: 'maven_3_8_6') {
		//			sh 'mvn -f com.corso.jenkins/pom.xml deploy'
		//		}
		//	}
		//}
	
		
		
	}

}